### ISSUE TITLE
Steel drum plays wrong notes in Firefox

### ISSUE THREAD

**Issue by sagamusix** [thenfour/digifujam#246]
One octave above middle-C, the steel drum instrument only plays C notes for any note you try to play. Only appears to happen in Firefox, may also affect other instruments.

**Comment by thenfour** [comment]
The issue was Firefox doesn't support "detune" for more than an octave. So for 1-sample SFZ instruments, the whole keyboard range isn't supported and the frequency gets clamped.

See: https://zpl.fi/pitch-shifting-in-web-audio-api/

> Firefox does support detune but its range is limited to one octave (see [Firefox bug 1624681](https://bugzilla.mozilla.org/show_bug.cgi?id=1624681)). This limitation comes from [an old specification of Web Audio API](https://www.w3.org/TR/2015/WD-webaudio-20151208/#widl-AudioBufferSourceNode-detune) so other browsers (or their old versions) may also have the same limitation.

solution is to use `playbackRate` instead of `detune` and now it works.
